name <- c("Amy","Bill","Carl")
DAD <- c(80,65,50)
BDA <- c(70,50,80)
gender <- as.factor(c("F","M","M"))
nationality <- as.factor(c("IRL","UK","IRL"))
age <- c(20,21,22)
student.df <- data.frame(name,DAD,BDA,gender,nationality,age)
student.df$averge <- (student.df$DAD + student.df$BDA)/2
student.df <- rbind(student.df,c("Dennis",70,50,"M","UK",23,70))
nationality <- as.character(nationality)
student.df <- rbind(student.df,c("Himanshu",80,90,"M","IRL",25,85),c("Amod",70,80,"M","IRL",25,75),c("Vidya",60,95,"F","UK",24,80))
nationality <- as.factor(nationality)
student.df$BDA <- as.numeric(student.df$BDA)
student.df$DAD <- as.numeric(student.df$DAD)
averages <- tapply(student.df$BDA, student.df$nationality,mean)
barplot(table(student.df$nationality),xlab = "Nationality", ylab = "Count")
Minimum <- c(min(student.df$DAD),min(student.df$BDA))
Maximum <- c(max(student.df$DAD),max(student.df$BDA))
Means <- c(mean(student.df$DAD),mean(student.df$BDA))
Standard.Deviation <- c(sd(student.df$DAD),sd(student.df$BDA))
results <- data.frame(Minimum,Maximum,Means,Standard.Deviation)
row.names(results) <- c("DAD","BDA")
mtcars$cyl <- as.factor(mtcars$cyl)
mtcars$am <- factor(mtcars$am, labels=c("Automatic", "Manual"), levels=c(0,1))
hist(mtcars$mpg ,breaks = 10)
boxplot(mtcars$hp)
coplot(mpg ~ hp | cyl, data = mtcars, panel = panel.smooth, rows = 1)
#1
mtcars$am <- as.character(mtcars$am)
print(table(mtcars$am))

